name: Snap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapd-repro-lp-snap
          path: ${{ steps.snapcraft.outputs.snap }}
